#!/usr/bin/env bash
set -euo pipefail

# Update the lockfile first, then update direct dependency requirements only
# within compatible semver ranges. Breaking upgrades are intentionally not
# forced unless the project already permits them.
cargo update

# Install cargo-edit only for manifest-aware upgrade reporting.
cargo install cargo-edit --locked
cargo upgrade
cargo update

cargo fmt --all -- --check
cargo check --all-targets
cargo test --all
cargo clippy --all-features --workspace -- -D warnings

{
  echo "# Dependency update report"
  echo
  echo "Generated by the bounty runner."
  echo
  echo "## Validation"
  echo
  echo "- cargo fmt --all -- --check"
  echo "- cargo check --all-targets"
  echo "- cargo test --all"
  echo "- cargo clippy --all-features --workspace -- -D warnings"
} > DEPENDENCY_UPDATE_REPORT.md
